# Generated by Django 5.1.1 on 2025-10-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0002_remove_landlord_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
