# Generated by Django 5.1.1 on 2025-10-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0003_alter_landlord_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landlord',
            options={'ordering': ['-first_name']},
        ),
    ]
