# Generated by Django 5.1.1 on 2025-09-20 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
        ('tenants', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantagreement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_agreements', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='tenantagreement',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_agreements', to='units.unit'),
        ),
    ]
