# Generated by Django 5.1.1 on 2025-10-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_alter_tenantagreement_tenant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantagreement',
            options={'ordering': ['tenant']},
        ),
    ]
