# Generated by Django 5.1.1 on 2025-09-20 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_property_delete_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=20)),
                ('unit_type', models.CharField(choices=[('single', 'Single'), ('double_room', 'Double Room'), ('bedsitter', 'Bedsitter')], default='single', max_length=30)),
                ('unit_build', models.CharField(choices=[('mabati', 'Mabati'), ('block', 'Block')], default='mabati', max_length=20)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unit_status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='vacant', max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
        ),
    ]
