# Generated by Django 5.1.1 on 2025-09-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='rent_status',
            field=models.CharField(choices=[('paid', 'paid'), ('overdue', 'overdue')], default='paid', max_length=50),
        ),
    ]
