# Generated by Django 5.1.1 on 2025-09-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_unit_rent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='rent_status',
            field=models.CharField(choices=[('paid', 'paid'), ('overdue', 'overdue'), ('--', '--')], default='paid', max_length=50),
        ),
    ]
