# Generated by Django 5.1.1 on 2025-09-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_alter_unit_rent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='rent_status',
            field=models.CharField(choices=[('paid', 'paid'), ('overdue', 'overdue'), ('vacant', 'vacant')], default='paid', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('single', 'Single'), ('double_room', 'Double Room'), ('bedsitter', 'Bedsitter'), ('one_bedroom', 'one_bedroom'), ('two_bedroom', 'two_bedroom')], default='single', max_length=30),
        ),
    ]
