# Generated by Django 5.1.1 on 2025-09-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_alter_unit_rent_status_alter_unit_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='rent_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('overdue', 'Overdue'), ('vacant', 'Vacant')], default='paid', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('single', 'Single'), ('double_room', 'Double room'), ('bedsitter', 'Bedsitter'), ('one_bedroom', 'One bedroom'), ('two_bedroom', 'Two bedroom')], default='single', max_length=30),
        ),
    ]
