# Generated by Django 5.2.6 on 2025-10-04 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_owner_property_landlord'),
        ('units', '0005_alter_unit_rent_status_alter_unit_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property'),
        ),
    ]
