# Generated by Django 5.2.6 on 2025-10-04 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_owner_property_landlord'),
        ('units', '0006_alter_unit_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property'),
            preserve_default=False,
        ),
    ]
