# Generated by Django 5.1.1 on 2025-10-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0007_alter_unit_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=59, null=True),
        ),
    ]
