# Generated by Django 5.1.1 on 2025-10-08 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0008_unit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='name',
        ),
    ]
