# Generated by Django 5.1.1 on 2025-10-15 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0010_remove_unit_rent_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['-unit_number']},
        ),
    ]
