# Generated by Django 5.2.6 on 2025-11-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0011_alter_unit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_build',
            field=models.CharField(choices=[('mabati', 'Mabati'), ('block', 'Block')], default='block', max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='occupied', max_length=20),
        ),
    ]
