# Generated by Django 5.1.4 on 2025-11-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0012_alter_unit_unit_build_alter_unit_unit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('shop', 'Shop'), ('single', 'Single'), ('double_room', 'Double room'), ('bedsitter', 'Bedsitter'), ('one_bedroom', 'One bedroom'), ('two_bedroom', 'Two bedroom')], default='single', max_length=30),
        ),
    ]
