# Generated by Django 5.1.1 on 2025-09-20 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_alter_property_owner'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('id_number', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(max_length=250)),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_tenants', to='units.unit')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_tenants', to='properties.property')),
            ],
        ),
    ]
