# Generated by Django 5.1.1 on 2025-09-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='Unit',
            new_name='unit',
        ),
    ]
