# Generated by Django 5.2.6 on 2025-10-04 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_rename_phone_tenant_phone_rename_unit_tenant_unit'),
        ('units', '0007_alter_unit_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='move_out_date',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='notes',
        ),
        migrations.AddField(
            model_name='tenant',
            name='deposit',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='units.unit'),
        ),
    ]
