# Generated by Django 5.2.6 on 2025-10-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_remove_tenant_move_out_date_remove_tenant_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='email',
        ),
    ]
