# Generated by Django 5.2.6 on 2025-10-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_remove_tenant_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='status',
        ),
    ]
