# Generated by Django 5.1.1 on 2025-10-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_remove_tenant_deposit_remove_tenant_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['-first_name']},
        ),
    ]
