# Generated by Django 5.2.6 on 2025-11-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_alter_tenant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
