# Generated by Django 5.2.6 on 2025-11-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_alter_tenant_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='last_name',
            field=models.CharField(blank=True, default='-', max_length=30, null=True),
        ),
    ]
