# Generated by Django 5.1.4 on 2025-11-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_alter_tenant_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
