# Generated by Django 5.1.1 on 2025-09-20 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0001_initial'),
        ('properties', '0002_property_delete_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlords.landlord'),
        ),
    ]
