# Generated by Django 5.1.1 on 2025-09-21 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0001_initial'),
        ('properties', '0003_alter_property_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='owner',
        ),
        migrations.AddField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='property_landlord', to='landlords.landlord'),
            preserve_default=False,
        ),
    ]
