# Generated by Django 5.1.1 on 2025-10-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_owner_property_landlord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-landlord']},
        ),
    ]
