# Generated by Django 5.1.1 on 2025-09-20 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreements', '0002_alter_tenantagreement_tenant_and_more'),
        ('tenants', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_payable', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rent_paid', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_method', models.CharField(choices=[('mpesa', 'Mpesa'), ('equity', 'Equity'), ('cash', 'Cash')], default='mpesa', max_length=20)),
                ('brought_forward', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('balance_carry_forward', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_payment', to='tenants.tenant')),
                ('tenant_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements_payments', to='agreements.tenantagreement')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_unit', to='units.unit')),
            ],
        ),
    ]
