# Generated by Django 5.1.1 on 2025-09-23 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_alter_tenantagreement_tenant_and_more'),
        ('financials', '0001_initial'),
        ('properties', '0004_remove_property_owner_property_landlord'),
        ('tenants', '0002_rename_phone_tenant_phone_rename_unit_tenant_unit'),
        ('units', '0004_alter_unit_rent_status_alter_unit_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_tenant', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('repairs', 'repairs'), ('utilities', 'utilities')], default='utilities', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(max_length=255)),
                ('date', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propery_expense', to='properties.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_expense', to='units.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateTimeField()),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_agreement', to='agreements.tenantagreement')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_unit_amount', to='units.unit')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_unit_status', to='units.unit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_tenant', to='tenants.tenant')),
            ],
        ),
    ]
