# Generated by Django 5.1.1 on 2025-09-25 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_alter_payment_tenant_expenses_invoice'),
        ('properties', '0004_remove_property_owner_property_landlord'),
        ('units', '0004_alter_unit_rent_status_alter_unit_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_property', to='properties.property'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_unit', to='units.unit'),
        ),
        migrations.AddField(
            model_name='payment',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_property', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('repairs', 'Repairs'), ('utilities', 'Utilities')], default='utilities', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_unit_status', to='units.unit'),
        ),
    ]
