# Generated by Django 5.1.1 on 2025-09-25 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_invoice_property_invoice_unit_payment_property_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='tenant_agreement',
        ),
    ]
