# Generated by Django 5.1.1 on 2025-09-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_remove_payment_tenant_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='agreement',
        ),
    ]
