# Generated by Django 5.1.1 on 2025-09-26 04:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_remove_invoice_agreement'),
        ('properties', '0004_remove_property_owner_property_landlord'),
        ('units', '0005_alter_unit_rent_status_alter_unit_unit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('previous_reading', models.CharField(max_length=100)),
                ('current_reading', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilities_property', to='properties.property')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilities_unit', to='units.unit')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
