# Generated by Django 4.0.10 on 2025-09-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0006_utilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='brought_forward',
            new_name='balance_brought_forward',
        ),
    ]
