# Generated by Django 5.2.6 on 2025-09-27 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0007_rename_brought_forward_payment_balance_brought_forward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='category',
        ),
    ]
