# Generated by Django 5.2.6 on 2025-09-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0008_remove_expenses_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilities',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
