# Generated by Django 5.2.6 on 2025-09-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0009_alter_utilities_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_issued',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
