# Generated by Django 5.2.6 on 2025-09-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0010_payment_date_issued_alter_expenses_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_issued',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_issued',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='date',
            field=models.DateField(),
        ),
    ]
