# Generated by Django 5.2.6 on 2025-09-27 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0011_alter_expenses_date_alter_invoice_date_issued_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
    ]
