# Generated by Django 5.2.6 on 2025-09-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0012_remove_invoice_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('overdue', 'Overdue'), ('vacant', 'Vacant')], default='paid', max_length=50),
        ),
    ]
