# Generated by Django 5.2.6 on 2025-09-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0013_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
