# Generated by Django 5.2.6 on 2025-10-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0014_invoice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deposit',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
