# Generated by Django 5.1.1 on 2025-10-08 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0015_payment_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='rent_paid',
            new_name='rent',
        ),
    ]
