# Generated by Django 5.1.1 on 2025-10-12 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0016_rename_rent_paid_payment_rent'),
        ('units', '0010_remove_unit_rent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_unit', to='units.unit'),
        ),
    ]
