# Generated by Django 5.1.1 on 2025-10-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0017_alter_payment_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rent_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('overdue', 'Overdue'), ('vacant', 'Vacant')], default='', max_length=50),
        ),
    ]
