# Generated by Django 5.2.6 on 2025-10-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0018_payment_rent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='balance_brought_forward',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='balance_carry_forward',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
    ]
