# Generated by Django 5.2.6 on 2025-10-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0019_alter_payment_balance_brought_forward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='balance_brought_forward',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='balance_carry_forward',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
