# Generated by Django 5.1.1 on 2025-10-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0020_alter_payment_balance_brought_forward_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date_issued']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date_issued']},
        ),
    ]
