# Generated by Django 5.2.6 on 2025-11-02 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0021_alter_expenses_options_alter_invoice_options_and_more'),
        ('properties', '0005_alter_property_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_expense', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
