# Generated by Django 5.2.6 on 2025-11-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0022_alter_expenses_property_alter_payment_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='name',
            new_name='expense_name',
        ),
    ]
