# Generated by Django 5.2.6 on 2025-11-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0023_rename_name_expenses_expense_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
